# Generated by Django 5.1 on 2024-09-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='response',
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.JSONField(default=list),
        ),
    ]
