# Generated by Django 5.1.1 on 2024-09-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_message_message_remove_message_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='Untitled Conversation', max_length=255),
        ),
    ]
